/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CajaChica;

import javax.swing.JOptionPane;

/**
 *
 * @author CLIENTE
 */
public class FrmTransaccion extends javax.swing.JFrame {

    /**
     * Creates new form FrmTransaccion
     */
    public FrmTransaccion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbTransaccion = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbTransaccion.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        cmbTransaccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una transaccion", "Solicitud", "Aprobacion", "Declaracion compra" }));
        cmbTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTransaccionActionPerformed(evt);
            }
        });
        getContentPane().add(cmbTransaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 340, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 57)); // NOI18N
        jLabel2.setText("Bienvenido");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, -1));

        btnIngresar.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 490, -1, -1));

        btnRegresar.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CajaChica/Imagenes/FondoLogin.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        FrmLogin regresar = new FrmLogin();
        regresar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void cmbTransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTransaccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTransaccionActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        if (cmbTransaccion.getSelectedIndex() == 1) {
            FrmSolicitud newSoli = new FrmSolicitud();
            newSoli.setVisible(true);
            this.setVisible(false);
            
        }
        if (cmbTransaccion.getSelectedIndex() == 2) {
            FrmAprobacion newApro = new FrmAprobacion();
            newApro.setVisible(true);
            this.setVisible(false);
            
        }
        if (cmbTransaccion.getSelectedIndex() == 3) {
            FrmCompra newCom = new FrmCompra();
            newCom.setVisible(true);
            this.setVisible(false);
            
        }
        if(cmbTransaccion.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(rootPane, "Por favor seleccione una transaccion");
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTransaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTransaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTransaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTransaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTransaccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbTransaccion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables
}
